# Generated by Django 6.0 on 2025-12-08 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('consultation_type', models.CharField(choices=[('phone', 'مشاوره تلفنی'), ('online', 'مشاوره آنلاین'), ('retired_judge', 'مشاوره با قاضی بازنشسته'), ('in_person', 'مشاوره حضوری')], max_length=20, verbose_name='نوع مشاوره')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع مشاوره')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('preferred_date', models.DateField(verbose_name='تاریخ پیشنهادی')),
                ('preferred_time', models.TimeField(verbose_name='ساعت پیشنهادی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'انجام شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خدمت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.CharField(max_length=50, verbose_name='آیکون (Font Awesome)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('hero_title', 'عنوان اصلی صفحه'), ('hero_subtitle', 'زیرعنوان اصلی صفحه'), ('about_text', 'متن درباره ما'), ('contact_info', 'اطلاعات تماس'), ('services', 'خدمات'), ('testimonials', 'نظرات مشتریان')], max_length=50, unique=True, verbose_name='نوع محتوا')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'محتوای سایت',
                'verbose_name_plural': 'محتوای سایت',
            },
        ),
        migrations.CreateModel(
            name='ConsultationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name='متن پاسخ')),
                ('response_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پاسخ')),
                ('is_final', models.BooleanField(default=False, verbose_name='پاسخ نهایی')),
                ('consultation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.consultationrequest', verbose_name='درخواست مشاوره')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='پاسخ\u200cدهنده')),
            ],
            options={
                'verbose_name': 'پاسخ مشاوره',
                'verbose_name_plural': 'پاسخ\u200cهای مشاوره',
                'ordering': ['response_date'],
            },
        ),
    ]
