# Generated by Django 6.0 on 2025-12-09 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(choices=[('phone', 'مشاوره تلفنی'), ('online', 'مشاوره آنلاین'), ('in_person', 'مشاوره حضوری'), ('retired_judge', 'مشاوره با قاضی بازنشسته')], max_length=20, unique=True, verbose_name='نوع مشاوره')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.CharField(max_length=50, verbose_name='آیکون (Font Awesome)')),
                ('features', models.TextField(blank=True, verbose_name='ویژگی\u200cها (هر ویژگی در خط جداگانه)')),
                ('button_text', models.CharField(max_length=50, verbose_name='متن دکمه')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='لینک دکمه')),
                ('button_color', models.CharField(default='primary', max_length=20, verbose_name='رنگ دکمه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نوع مشاوره',
                'verbose_name_plural': 'انواع مشاوره',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات بیشتر')),
                ('category', models.CharField(choices=[('family', 'خانواده'), ('criminal', 'کیفری'), ('civil', 'مدنی'), ('labor', 'کار و کارگر'), ('real_estate', 'املاک و مستغلات'), ('commercial', 'تجاری'), ('other', 'سایر')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('questioner_name', models.CharField(blank=True, max_length=100, verbose_name='نام پرسشگر')),
                ('is_answered', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'سوال اخیر',
                'verbose_name_plural': 'سوالات اخیر',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('short_answer', models.TextField(help_text='این متن در صفحه اصلی نمایش داده می\u200cشود', verbose_name='خلاصه پاسخ')),
                ('lawyer_title', models.CharField(default='وکیل پایه یک', max_length=100, verbose_name='عنوان وکیل')),
                ('icon', models.CharField(default='fas fa-gavel', max_length=50, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('lawyer', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='وکیل')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.recentquestion', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ وکیل',
                'verbose_name_plural': 'پاسخ\u200cهای وکلا',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
